from __future__ import annotations

import ast
import json
import os
import re
import subprocess
import sys
from pathlib import Path

import pytest

from iai_mcp.capture import _NOISE_PATTERNS, _parse_transcript_line

HOOK_FILE = (
    Path(__file__).resolve().parent.parent
    / "src" / "iai_mcp" / "_deploy" / "hooks" / "iai-mcp-turn-capture.sh"
)


def _user_line(text: str, **extra) -> str:
    obj = {"type": "user", "message": {"role": "user", "content": text}}
    obj.update(extra)
    return json.dumps(obj)


def _hook_py_script() -> str:
    m = re.search(r"PY_SCRIPT='(.*?)'\s*\n", HOOK_FILE.read_text(), re.DOTALL)
    assert m, f"PY_SCRIPT heredoc not found in {HOOK_FILE}"
    return m.group(1)


def _hook_noise_tuples() -> tuple[tuple[str, ...], tuple[str, ...]]:
    tree = ast.parse(_hook_py_script())
    found: dict[str, tuple[str, ...]] = {}
    for node in ast.walk(tree):
        if not isinstance(node, ast.Assign) or len(node.targets) != 1:
            continue
        target = node.targets[0]
        if isinstance(target, ast.Name) and target.id in ("_NOISE_STARTSWITH", "_NOISE_EQUALS"):
            found[target.id] = tuple(ast.literal_eval(node.value))
    assert set(found) == {"_NOISE_STARTSWITH", "_NOISE_EQUALS"}, found
    return found["_NOISE_STARTSWITH"], found["_NOISE_EQUALS"]


def test_hook_noise_filter_mirrors_capture():
    hook_prefixes, hook_exacts = _hook_noise_tuples()
    capture_prefixes = tuple(p for kind, p in _NOISE_PATTERNS if kind == "startswith")
    capture_exacts = tuple(p for kind, p in _NOISE_PATTERNS if kind == "equals")
    assert hook_prefixes == capture_prefixes, (
        "hook _NOISE_STARTSWITH drifted from capture._NOISE_PATTERNS"
    )
    assert hook_exacts == capture_exacts, (
        "hook _NOISE_EQUALS drifted from capture._NOISE_PATTERNS"
    )


@pytest.mark.parametrize(
    "text",
    [
        "<local-command-caveat>Caveat: The messages below were generated by the "
        "user while running local commands. DO NOT respond to these messages or "
        "otherwise consider them in your response unless the user explicitly asks "
        "you to.</local-command-caveat>",
        "<local-command-stdout>Set model to claude-opus-4-8</local-command-stdout>",
        "<local-command-stderr>no such model</local-command-stderr>",
        "<command-args>claude-opus-4-8</command-args>",
        "<command-name>/model</command-name>\n            <command-message>model"
        "</command-message>\n            <command-args>claude-opus-4-8</command-args>",
    ],
)
def test_local_command_lines_dropped(text: str):
    result = _parse_transcript_line(_user_line(text))
    assert result is None, (
        f"local-command line should be filtered (got {result!r}); "
        "_parse_transcript_line must apply the noise filter"
    )


def test_is_meta_line_dropped():
    line = _user_line(
        "please remember that the release gate is the sequential lilli run",
        isMeta=True,
    )
    result = _parse_transcript_line(line)
    assert result is None, (
        f"isMeta line should be filtered (got {result!r}); host-injected "
        "pseudo-turns are never dialogue"
    )


def test_is_meta_false_line_preserved():
    genuine_text = "please remember that the release gate is the sequential lilli run"
    result = _parse_transcript_line(_user_line(genuine_text, isMeta=False))
    assert result is not None
    assert result[1] == genuine_text


def test_hook_drops_local_command_sequence_and_meta(tmp_path: Path):
    """The inline hook must spool ONLY the genuine prompts around a /model switch."""
    sid = "noise-filter-hook-session"
    home = tmp_path
    (home / ".iai-mcp" / ".capture-state").mkdir(parents=True)
    (home / ".iai-mcp" / ".deferred-captures").mkdir(parents=True)
    transcript = home / "transcript.jsonl"
    caveat = (
        "<local-command-caveat>Caveat: The messages below were generated by the "
        "user while running local commands. DO NOT respond to these messages or "
        "otherwise consider them in your response unless the user explicitly asks "
        "you to.</local-command-caveat>"
    )
    lines = [
        _user_line("why is the working tier goal polluted after a model switch",
                   uuid="u1", timestamp="2026-08-17T16:22:43.911Z"),
        _user_line("[Request interrupted by user]", uuid="u2",
                   timestamp="2026-08-17T16:23:06.000Z"),
        _user_line(caveat, uuid="u3", timestamp="2026-08-17T16:23:08.000Z", isMeta=True),
        _user_line("<command-name>/model</command-name>\n            <command-message>"
                   "model</command-message>\n            <command-args>claude-opus-4-8"
                   "</command-args>", uuid="u4", timestamp="2026-08-17T16:23:08.000Z"),
        _user_line("<local-command-stdout>Set model to claude-opus-4-8"
                   "</local-command-stdout>", uuid="u5",
                   timestamp="2026-08-17T16:23:08.000Z"),
        _user_line("fix the injection", uuid="u6", timestamp="2026-08-17T16:23:35.000Z"),
    ]
    transcript.write_text("\n".join(lines) + "\n")

    env = dict(os.environ, HOME=str(home))
    proc = subprocess.run(
        [sys.executable, "-c", _hook_py_script(), sid, str(transcript)],
        env=env, capture_output=True, text=True, timeout=30,
    )
    assert proc.returncode == 0, proc.stderr

    live = home / ".iai-mcp" / ".deferred-captures" / f"{sid}.live.jsonl"
    events = [json.loads(ln) for ln in live.read_text().splitlines() if ln.strip()]
    turns = [e for e in events if "role" in e]
    assert [t["text"] for t in turns] == [
        "why is the working tier goal polluted after a model switch",
        "fix the injection",
    ], turns
    assert [t["source_uuid"] for t in turns] == ["u1", "u6"]


def test_command_message_dropped():
    line = _user_line("<command-message>gsd-map-codebase</command-message>")
    result = _parse_transcript_line(line)
    assert result is None, (
        f"command-message line should be filtered (got {result!r}); "
        "_parse_transcript_line must apply the noise filter"
    )


def test_skill_injection_dropped():
    line = _user_line("Base directory for this skill: /Users/alice/Desktop/ASSET")
    result = _parse_transcript_line(line)
    assert result is None, (
        f"skill-injection line should be filtered (got {result!r}); "
        "_parse_transcript_line must apply the noise filter"
    )


def test_task_notification_dropped():
    line = _user_line("<task-notification>\n<task-id>abc123</task-id>\n</task-notification>")
    result = _parse_transcript_line(line)
    assert result is None, (
        f"task-notification line should be filtered (got {result!r}); "
        "_parse_transcript_line must apply the noise filter"
    )


def test_interrupted_dropped():
    line = _user_line("[Request interrupted by user]")
    result = _parse_transcript_line(line)
    assert result is None, (
        f"interrupted marker should be filtered (got {result!r}); "
        "_parse_transcript_line must apply the noise filter"
    )


def test_genuine_line_preserved():
    genuine_text = "what was the session identifier for the last worktree build"
    line = _user_line(genuine_text)
    result = _parse_transcript_line(line)
    assert result is not None, "genuine user line must not be filtered"
    role, text, *_ = result
    assert role == "user"
    assert text == genuine_text, (
        f"verbatim text was altered (got {text!r}, expected {genuine_text!r})"
    )


def test_genuine_line_quoting_marker_preserved():
    genuine_text = "I saw <task-notification> appear in the logs yesterday"
    line = _user_line(genuine_text)
    result = _parse_transcript_line(line)
    assert result is not None, (
        "genuine user line containing a noise substring must not be filtered; "
        "byte-identical storage of real user turns is required"
    )
    role, text, *_ = result
    assert role == "user"
    assert text == genuine_text


# ---------------------------------------------------------------------------
# Key-scheme lockstep: role:user turns key by promptId (fallback uuid);
# role:assistant turns stay keyed by uuid in BOTH walkers.
# ---------------------------------------------------------------------------

def test_parse_transcript_line_user_keyed_by_prompt_id():
    text = "genuine enough text for the key scheme lockstep test right here"
    line = _user_line(text, uuid="u-per-line", promptId="p-per-prompt")
    result = _parse_transcript_line(line)
    assert result is not None
    role, out_text, src_uuid, _ts = result
    assert role == "user"
    assert out_text == text
    assert src_uuid == "p-per-prompt", (
        "capture.py's daemon/Stop-hook walk must key role:user by promptId"
    )


def test_parse_transcript_line_user_falls_back_to_uuid_without_prompt_id():
    text = "genuine enough text with no prompt id present on this line at all"
    line = _user_line(text, uuid="u-per-line-only")
    result = _parse_transcript_line(line)
    assert result is not None
    role, _out_text, src_uuid, _ts = result
    assert role == "user"
    assert src_uuid == "u-per-line-only", (
        "promptId absent must fall back to uuid, never leave the key None"
    )


def test_parse_transcript_line_assistant_keyed_by_uuid_not_prompt_id():
    obj = {
        "type": "assistant",
        "message": {"role": "assistant", "content": "assistant reply text long enough here"},
        "uuid": "u-assistant-line",
        "promptId": "p-shared-by-whole-response",
    }
    result = _parse_transcript_line(json.dumps(obj))
    assert result is not None
    role, _out_text, src_uuid, _ts = result
    assert role == "assistant"
    assert src_uuid == "u-assistant-line", (
        "assistant lines of one prompt share promptId — keying them by "
        "promptId would collapse a whole response into one idem"
    )


def _hook_key_scheme_transcript_line(role: str, text: str, *, uuid: str, prompt_id: str) -> str:
    obj = {"type": role, "message": {"role": role, "content": text},
           "uuid": uuid, "promptId": prompt_id}
    return json.dumps(obj)


def _run_hook_key_scheme(tmp_path: Path, sid: str, lines: list[str]) -> list[dict]:
    home = tmp_path / f"home-{sid}"
    (home / ".iai-mcp" / ".capture-state").mkdir(parents=True)
    (home / ".iai-mcp" / ".deferred-captures").mkdir(parents=True)
    transcript = home / "transcript.jsonl"
    transcript.write_text("\n".join(lines) + "\n")

    env = dict(os.environ, HOME=str(home))
    proc = subprocess.run(
        [sys.executable, "-c", _hook_py_script(), sid, str(transcript)],
        env=env, capture_output=True, text=True, timeout=30,
    )
    assert proc.returncode == 0, proc.stderr

    live = home / ".iai-mcp" / ".deferred-captures" / f"{sid}.live.jsonl"
    events = [json.loads(ln) for ln in live.read_text().splitlines() if ln.strip()]
    return [e for e in events if "role" in e]


def test_hook_walk_user_turn_keyed_by_prompt_id(tmp_path: Path):
    text = "hook-side walk must key this user turn by its promptId not uuid"
    lines = [_hook_key_scheme_transcript_line(
        "user", text, uuid="hook-per-line-uuid", prompt_id="hook-per-prompt-id",
    )]
    turns = _run_hook_key_scheme(tmp_path, "key-scheme-user", lines)
    assert len(turns) == 1
    assert turns[0]["source_uuid"] == "hook-per-prompt-id"


def test_hook_walk_assistant_turn_keyed_by_uuid_not_prompt_id(tmp_path: Path):
    text = "hook-side walk must keep this assistant turn keyed by its own uuid"
    lines = [_hook_key_scheme_transcript_line(
        "assistant", text, uuid="hook-assistant-uuid", prompt_id="hook-shared-prompt-id",
    )]
    turns = _run_hook_key_scheme(tmp_path, "key-scheme-assistant", lines)
    assert len(turns) == 1
    assert turns[0]["source_uuid"] == "hook-assistant-uuid"


# ---------------------------------------------------------------------------
# Immediate-path noise: the raw-slash guard — a slash-command prompt arrives
# as RAW text on stdin (`/command`), not expanded <command-*> markup — plus
# the existing _is_noise mirror.
# ---------------------------------------------------------------------------

def _immediate_payload_run(tmp_path: Path, sid: str, prompt: str, prompt_id: str) -> list[dict]:
    home = tmp_path / f"home-imm-{sid}"
    (home / ".iai-mcp" / ".capture-state").mkdir(parents=True)
    (home / ".iai-mcp" / ".deferred-captures").mkdir(parents=True)
    # Filler transcript line: keeps this helper representative of the
    # common case where a transcript already exists alongside the immediate
    # capture. First-fire (no transcript at all) is covered separately.
    transcript = home / "transcript.jsonl"
    transcript.write_text(_user_line("unrelated filler turn for transcript resolution") + "\n")
    payload = home / "payload.json"
    payload.write_text(json.dumps({"prompt": prompt, "prompt_id": prompt_id}), encoding="utf-8")

    env = dict(os.environ, HOME=str(home))
    proc = subprocess.run(
        [sys.executable, "-c", _hook_py_script(), sid, str(transcript), str(payload), prompt_id],
        env=env, capture_output=True, text=True, timeout=30,
    )
    assert proc.returncode == 0, proc.stderr

    live = home / ".iai-mcp" / ".deferred-captures" / f"{sid}.live.jsonl"
    events = [json.loads(ln) for ln in live.read_text().splitlines() if ln.strip()]
    return [e for e in events if "role" in e]


def test_immediate_path_drops_raw_slash_command(tmp_path: Path):
    prompt = "/deploy extra padding so length clears the floor"
    prompt_id = "slash-guard-prompt-id-0001"
    turns = _immediate_payload_run(tmp_path, "slash-guard-hook", prompt, prompt_id)
    # only the unrelated filler turn from the transcript walk, no immediate line
    assert not any(t.get("source_uuid") == prompt_id for t in turns), (
        "a raw leading-slash prompt must not reach the immediate spool — "
        "the stdin prompt for a /command arrives RAW (confirmed live), "
        "not expanded <command-*> markup"
    )


def test_immediate_path_writes_genuine_prompt(tmp_path: Path):
    prompt = "please tighten the immediate capture path for this real test"
    prompt_id = "genuine-immediate-prompt-id-0002"
    turns = _immediate_payload_run(tmp_path, "genuine-immediate-hook", prompt, prompt_id)
    matches = [t for t in turns if t.get("source_uuid") == prompt_id]
    assert len(matches) == 1, turns
    assert matches[0]["text"] == prompt
    assert matches[0]["role"] == "user"
