# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
__all__ = [
    "Embedder",
]

@typing.final
class Embedder:
    r"""
    Rust BERT embedder for BAAI/bge-small-en-v1.5 (384-dim L2-normalized output).
    
    Constructed eagerly: weights load from the HF cache in `__new__`. If
    `IAI_MCP_EMBED_OFFLINE=1` is set, construction fails loudly when any
    required file is missing rather than triggering a silent network download.
    
    The `module` attribute attributes this class to `iai_mcp_native.embed`
    in the generated `.pyi` stub — pyo3-stub-gen derives parent/child module
    relationships from these dotted names so a single stub file can describe
    the sub-module tree consumed at runtime.
    """
    def __new__(cls, model_id: typing.Optional[builtins.str] = None, revision: typing.Optional[builtins.str] = None, pool: typing.Optional[builtins.str] = None) -> Embedder:
        r"""
        Load bge-small-en-v1.5 weights from the HF cache (lazy download on miss
        unless `IAI_MCP_EMBED_OFFLINE=1`).
        
        The GIL is released for the duration of the model load so that
        background warm threads cannot block the main thread.
        `BertEmbedder::load` is pure Rust and holds no Python objects,
        making this safe.
        """
    def encode(self, text: builtins.str) -> builtins.list[builtins.float]:
        r"""
        Encode a single text string to a 384-dim L2-normalized vector.
        
        The GIL is released for the duration of the BERT forward pass so that
        concurrent socket clients dispatched via `asyncio.to_thread` can run
        their inference in parallel. `BertEmbedder::encode` is pure Rust and
        holds no Python objects, making this safe.
        """

